data:
  root: "/content/data"
  num_workers: 4

model:
  num_classes: 200
  dropout: 0.3

training:
  batch_size: 16
  lr: 0.003
  weight_decay: 0.0001
  max_lr: 0.0015
  num_epochs: 1
  log_dir: "./runs/CUB200_experiment"
  save_dir: "./checkpoints"
