# Generated by Django 5.1.6 on 2025-02-12 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("training_loss", models.FloatField()),
                ("validation_loss", models.FloatField()),
                ("accuracy", models.FloatField()),
                ("classification_report", models.TextField()),
            ],
        ),
    ]
